spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

    cloud:
      stream:
        bindings:
          saveLocation-in-0:
            destination: save-location
            group: save-group
          updateLocation-in-0:
            destination: update-location
            group: update-group
          deleteLocation-in-0:
            destination: delete-location
            group: delete-group
        rabbit:
          bindings:
            saveLocation-in-0:
              consumer:
                auto-bind-dlq: true
            updateLocation-in-0:
              consumer:
                auto-bind-dlq: true
            deleteLocation-in-0:
              consumer:
                auto-bind-dlq: true

viacep:
  url: ${VIACEP_URL:https://viacep.com.br/ws}
